services:
  - type: web
    name: traffic-api
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"

  - type: web
    name: traffic-streamlit
    runtime: python
    plan: free
    rootDir: frontend
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: BACKEND_URL
        sync: false
